apiVersion: apps/v1
kind: Deployment
metadata:
  name: multipaper-server 
  labels:
    app: multipaper-instance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multipaper-instance
  template:
    metadata:
      labels:
        app: multipaper-instance
    spec:
      containers:
      - name: multipaper-instance
        image: nik012003/multipaper-server:latest
        imagePullPolicy: Always
        env:
        - name: MASTER_ADDRESS
          value: multipaper-master
        - name: SERVER_PROPIETIES
          value: '{"online-mode":"false","allow-flight":"true","max-players":"200"}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multipaper-master 
  labels:
    app: multipaper-master
spec:
  selector:
    matchLabels:
      app: multipaper-master
  template:
    metadata:
      labels:
        app: multipaper-master
    spec:
      volumes:
        - name: master-volume
          hostPath:
            path: /opt/master-volume
      containers:
      - name: multipaper-master
        image: nik012003/multipaper-master:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: master-volume
          mountPath: /opt/storage
---
apiVersion: v1
kind: Service
metadata:
  name: multipaper-master
spec:
  ports:
  - port: 35353
  selector:
    app: multipaper-master
